import psycopg2
from urllib.parse import unquote

# Database connection
password = unquote("Mehar%406378110608")

# Broker names with their DSA codes
brokers_data = [
    ("PRAVEEN", "1"),
    ("Param Preet", "2"),
    ("Mukesh Yadav - Tractor", "3"),
    ("Rakesh Bagru - Tractor", "4"),
    ("MANOJ KUMAR SHARMA", "5"),
    ("Ajay Singh ,Ajmer", "6"),
    ("Prem Sukh", "7"),
    ("MUKESH KUMAR CHOUDHARY", "8"),
    ("VIJAYLAXMI YADAV", "9"),
    ("KAMLESH SHARMA", "10"),
    ("CP Soni", "11"),
    ("POOJA FINSERV", "12"),
    ("Shubha Karan - Shubham", "13"),
    ("Mukesh Chaudhary - Phulera", "14"),
    ("SHUBHAM", "15"),
    ("DHANLAXMI ASSOCIATES", "16"),
    ("MANISH KUMAR", "17"),
    ("Suresh Chand - Malpura", "18"),
    ("SHANKAR LAL", "19"),
    ("Sandeep Pathak", "20"),
    ("VINAY SINGH RAJAWAT", "21"),
    ("Pradeep Jangid", "22"),
    ("POONAM SEKHAWAT", "23"),
    ("Raghvendra", "24"),
    ("Gurdas Singh", "25"),
    ("RD FINSERVE", "26"),
    ("VISHNU KUMAR SHARMA", "27"),
    ("MANU", "28"),
    ("Gan Laxmi", "29"),
    ("Gyanendra", "30"),
    ("RAJESH GURJAR", "31"),
    ("MUKESH KUMAR JAT", "32"),
    ("Sunil - Lunkaransar", "33"),
    ("Balram", "34"),
    ("Ramkishan", "35"),
    ("Rajkumar Gurjar", "36"),
    ("Kapil", "37"),
    ("Kushveer", "38"),
    ("Rakesh Kameria", "39"),
    ("Ravi Sahu", "40"),
    ("DEEPAK YADAV", "41"),
    ("SUNNY SAHU", "42"),
    ("Pawan Tractor Hanumangarh", "43"),
    ("MAHADEV TRACTORS", "44"),
    ("DANISH KHAN", "45"),
    ("TUSHAR", "46"),
    ("Amit Sharma Tractor", "47"),
    ("Mohan Mahajan", "48"),
    ("RAJA RAM JAT", "49"),
    ("MAHENDRA SAIN", "50"),
    ("TUSHAR JAGGA", "51"),
    ("shiva", "52"),
    ("Pradeep Buri SK Kalwar", "53"),
    ("Virendra Singh", "54"),
    ("sarthi", "55"),
    ("NAND KISHORE JANGID", "56"),
    ("HITESH VERMA", "57"),
    ("MAHENDRA (KOGTA)", "58"),
    ("NOMAN KHAN", "59"),
    ("DEEPAK SHARMA", "60"),
    ("AKRAM", "61"),
    ("SHREE SHYAM MOTOARS", "62"),
    ("ROSHAN KUMAR MEENA", "63"),
    ("BABY SHARMA", "64"),
    ("MB FINANCE", "65"),
    ("BHANU PRIYA SHARMA", "66"),
    ("GARVIT JOLLY", "67"),
    ("SUKHDEV BAN", "68"),
    ("NARENDRA YADAV", "69"),
    ("RAVI KUMAR BUNKAR", "70"),
    ("VIKRAM", "71"),
    ("RAM RAJ CHOUDHARY", "72"),
    ("GORI SHANKAR", "73"),
    ("RAJU CHOPRA", "74"),
    ("KAMLESH", "75"),
    ("PRAMOD KUMAR", "76"),
    ("MANISH JOSHI", "77"),
    ("SHRI BALA JI E MITRA", "78"),
    ("MUSTAFA RAJA", "79"),
    ("VIJAY KUMAR", "80"),
    ("RAM NIWAS", "81"),
    ("RAJENDER RAJENDER", "82"),
    ("NAVNEET KUMAR", "83"),
    ("HARJINDER SINGH", "84"),
    ("SUKHVEER SINGH", "85"),
    ("KULDEEP KHICHA", "86"),
    ("ANGAD KUMAR", "87"),
    ("KULDEEP SINGH (HMH)", "88"),
    ("DINESH KUMAR", "89"),
    ("PANKAJ", "90"),
    ("PULKIT", "91"),
    ("KARISHNA DEVI", "92"),
    ("DEEPAK (HMH)", "93"),
    ("KAKA SINGH (HMH)", "94"),
    ("GURSEVAK SINGH", "95"),
    ("NITU", "96"),
    ("DHARM PAL", "97"),
    ("JAGDEEP SINGH", "98"),
    ("SHYAMSUNDER", "99"),
    ("MOHAMMED RAMJAN", "100"),
    ("PREM KUMAR(RAWATSAR)", "101"),
    ("SURENDER KUMAR (TIBBI)", "102"),
    ("BHANI RAM SWAMY", "103"),
    ("VIJAY KUMAR(HMH)", "104"),
    ("SANJU VERMA(ELLENABAD)", "105"),
    ("VINOD KUMAR", "106"),
    ("SHIV CAR BAZAR", "107"),
    ("PRAMOD KUMAR", "108"),
    ("SANDEEP KUMAR", "109"),
    ("DEVENDER SINGH", "110"),
    ("KARISHAN KUMAR", "111"),
    ("MANJU DEVI", "112"),
    ("FINFLY ADVISORS PRIVATE LIMITED", "113"),
    ("ANIL SHARMA", "114"),
    ("REETU SINGH", "115"),
    ("OM PRAKASH", "116"),
    ("POONAM DEVI", "117"),
    ("DAULT RAM", "118"),
    ("RAM DAYAL SIHAG", "119"),
    ("INDU BALA", "120"),
    ("ANIL KUMAR", "121"),
    ("SANJEEV KUMAR", "122"),
    ("RJ31 CAR BAJAR", "123"),
    ("ABDUL AZIZ", "124"),
    ("AMMI LAL YADAV", "125"),
    ("AMIT KUMAR", "126"),
    ("PVR CAR BAZAR", "127"),
    ("VIMLA SHANKAR", "128"),
    ("VINOD KUMAR", "129"),
    ("ROHITASH BANIWAL", "130"),
    ("SUNIL KUMAR", "131"),
    ("CHANDERBHAN", "132"),
    ("POOJA CHOUDHARY", "133"),
    ("RAKESH", "135"),
    ("JITENDRA KUMAR", "136"),
    ("MAMTA", "137"),
    ("MAHENDER SINGH", "138"),
    ("AMAR", "139"),
    ("PRAVIN KUMAR", "140"),
    ("PRIYANKA", "141"),
    ("VIKRAM BANGAWAD", "142"),
    ("DEVENDAR SINGH", "143"),
    ("MADAN LAL", "144"),
    ("PRAMOD KUMAR", "145"),
    ("SUSHILA", "148"),
    ("KAPIL BHARDWAJ", "149"),
    ("RITESH KUMAR", "150"),
    ("BHAVANI SINGH", "151"),
    ("PARVINDER SINGH", "152"),
    ("ANIL KUMAR", "153"),
    ("MITIN LAL", "154"),
    ("RAMKUMAR", "155"),
    ("RAHUL KUMAR", "156"),
    ("PRADEEP", "157"),
    ("VIRANDAR KUMAR", "158"),
    ("SHRIRAMFINSERV", "159"),
    ("GANESH KUMAR", "160"),
    ("YOGESH KUMAR", "161"),
    ("YOGESH KUMAR (HMH)", "162"),
    ("VIJAY KUMAR", "163"),
    ("VINOD", "165"),
    ("KANTA", "166"),
    ("Mohammad Aaruf", "167"),
    ("RAVI", "168"),
    ("VINOD KUMAR", "169"),
    ("SUNITA", "170"),
    ("LOVEDEEP SINGH", "171"),
    ("PREM KUMAR", "172"),
    ("KULDEEP", "173"),
    ("DAYA RAM", "174"),
    ("RAJENDERA SANKHI", "175"),
    ("OM PRAKASH", "176"),
    ("GURU KRIPA CAR BAZAR", "177"),
    ("MANJEET KUMAR", "178"),
    ("VANITA BHARADWAJ", "179"),
    ("GURPREET BAGRI", "180"),
    ("DEV KAUSHIK", "181"),
    ("DIWAN SINGH", "182"),
    ("JITENDER RAO", "183"),
    ("SURESH KUMAR", "184"),
    ("SUBHASH CHAND GURJAR", "185"),
    ("RAJPAL THORI", "186"),
    ("NEELAM SAIN", "187"),
    ("AJAY DEV", "188"),
    ("VINOD KUMAR", "189"),
    ("Ramdev Escorts", "190"),
    ("CHINDER PAL", "191"),
    ("RAMAN DEEP", "192"),
    ("SUSHILA RANI", "193"),
    ("KALU RAM SHARMA", "194"),
    ("AJMAL SINGH", "197"),
    ("SHISHPAL", "198"),
    ("KAMAL", "199"),
    ("VIMLA KANWAR", "200"),
    ("BHANWARI", "201"),
    ("VISHAL SHARMA", "202"),
    ("ASHOK CHOUDHARY", "203"),
    ("RENU SHARMA", "204"),
    ("PRABHAT BATRA", "205"),
    ("BALVINDER SINGH", "206"),
    ("RAM NIWAS PRAJAPAT", "210"),
    ("AASAK KHAN", "211"),
    ("SANDEEP GODARA", "212"),
    ("LALIT GODARA", "213"),
    ("DEEPAK CHOUDHARY", "214"),
    ("VINOD KUMAR", "215"),
    ("PANKAJ SHARMA", "216"),
    ("NIRANJANA KANWAR", "217"),
    ("MUKESH", "218"),
    ("MANISH VERMA", "219"),
    ("NISHA", "220"),
    ("SATPAL", "221"),
    ("PAWAN KUMAR", "222"),
    ("MUSE KHAN", "223"),
    ("DEVENDAR SINGH", "224"),
    ("AMITA", "225"),
    ("SHER SINGH TAWANR", "226"),
    ("VINAY KUMAR", "227"),
    ("Pradeep Kumar Meena", "228"),
    ("MAYA", "229"),
    ("VISHAL KUMAR", "230"),
    ("KHUDA BAKSH", "231"),
    ("MANISH KUMAR SAINI", "232"),
    ("RAMESHWAR LAL BISHNOI", "233"),
    ("MUKESH VERMA", "234"),
    ("PREM RATAN BISSA", "235"),
    ("RAMESHWAR", "236"),
    ("SHREE KRISHANA FINANCE", "237"),
    ("PRITAM PAL", "238"),
    ("SAKIR HUSAIN", "239"),
    ("CHHOTU RAM GURJAR", "240"),
    ("SURESH PHALOD", "241"),
    ("SOURABH GAHLOT", "242"),
    ("SITARAM", "243"),
    ("JITESH SHARMA", "244"),
    ("OM ENTERPRISES", "245"),
    ("RAJ PAL SINGH", "246"),
    ("AMIT KUMAR", "247"),
    ("SUMAN", "248"),
    ("KULDEEP PARJAPAT", "249"),
    ("MANDEEP KAUR", "250"),
    ("MANGAL JOSHI", "251"),
    ("RAMKUNWAR BISHNOI", "252"),
    ("SUMAN", "253"),
    ("ROHIT KUMAR PANCHARIYA", "254"),
    ("GEETA KANWAR", "255"),
    ("SANTOSH BHATI", "256"),
    ("JETHA RAM SIYAG", "257"),
    ("VAIBHAV GUPTA", "258"),
    ("Zabbir Ahmad", "259"),
    ("Reena kanwar", "260"),
    ("Vimla kumawat", "261"),
    ("Khemraj Kumawat", "262"),
    ("Rajkumar Swami", "263"),
    ("Akee", "264"),
    ("Bajrang lal upadhyay", "265"),
    ("Kajal sankhala", "266"),
    ("Munsab Ali", "267"),
    ("Rajesh kumar", "268"),
    ("Kalpna", "269"),
    ("jai shree upadhyay", "270"),
    ("kapil dev", "271"),
    ("Barkat Ali", "272"),
    ("Darshan Vyas", "273"),
    ("Roshan Kumar Meena", "274"),
    ("Kishan Singh", "275"),
    ("SANWAR MAL YADAV", "276"),
    ("RAMAVTAR", "277"),
    ("BARKAT", "278"),
    ("Sunita Devi", "279"),
    ("AAYAT CONSTRUCTION CO", "280"),
    ("KAILASH SHARMA", "281"),
    ("VIJAY PAL", "282"),
    ("FIROJ KHAN", "283"),
    ("SANDEEP", "284"),
    ("Shahnawaz", "285"),
    ("SONU KUMARI", "286"),
    ("BRIJESH DABI", "287"),
    ("Khushbu Gujar", "288"),
    ("Aslam Khan", "289"),
    ("Ramjan Khan", "290"),
    ("HITESH GUPTA", "291"),
    ("AMITA DEVI VYAS", "292"),
    ("SUMER", "293"),
    ("Punam Singh Chouhan", "294"),
    ("Kamal Kishore Jakhar", "295"),
    ("BALRAJ CHANGRA", "296"),
    ("PRIYANKA KANWAR", "297"),
    ("Navaratan Bhakar", "298"),
    ("DHARMPAL", "299"),
    ("RAM SUKH", "300"),
    ("HARI RAM KUKANA", "301"),
    ("ROHIT", "302"),
    ("PANKAJ SANKHLA", "303"),
    ("Shankar Lal Yadav", "304"),
    ("Kamlesh Kumar", "305"),
    ("SKFC FINANCE", "306"),
    ("Surender", "307"),
    ("Ratan Kumar", "308"),
    ("Deendyal", "309"),
    ("HANSRAJ", "310"),
    ("RAMESH MEENA", "311"),
    ("PAWAN KUMAR", "312"),
    ("RAMNIWAS BENIWAL", "313"),
    ("Lovepreet Singh", "314"),
    ("MAHAVIR", "315"),
    ("SARITA", "316"),
    ("KAMLESH KANWAR", "317"),
    ("JAVED ALI", "318"),
    ("SHRI RAM SIHAG", "319"),
    ("DEVENDER KUMAR", "320"),
    ("SHRI MARUTI NANDAN FINANCE", "321"),
    ("MANGAT RAM", "322"),
    ("Pooja", "323"),
    ("GAYATRI DEVI", "324"),
    ("FRIENDS ASSOCIATES", "325"),
    ("krishan kumar", "326"),
    ("SHREE SPEEDWAY MOTORS", "327"),
    ("GEETA SHARMA", "328"),
    ("SUMAN DEVI", "329"),
    ("MOHD SAZED", "330"),
    ("SANJU SHEKHAWAT", "331"),
    ("BHAWARI", "332"),
    ("MANOJ SINGH TANWAR", "333"),
    ("MEENA DERASARI", "334"),
    ("SONA DEVI", "335"),
    ("HUKMA RAM", "336"),
    ("HEENA", "337"),
    ("GAURAV KUMAR VERMA", "338"),
    ("ANKUSH", "339"),
    ("KOUSHALYA", "340"),
    ("MUNEER AHMED", "341"),
    ("RAHUL RANJAN", "342"),
    ("MADHU", "343"),
    ("VINOD KUMAR", "344"),
    ("ASHAKAR KHAN", "345"),
    ("PRIYANKA", "346"),
    ("AMIT KUMAR", "347"),
    ("SAKIL AHMED", "348"),
    ("PURNENDU SINGH NAROOKA", "349"),
    ("RISHABH DEV SINGH", "350"),
    ("OM SINGH", "351"),
    ("SUNIL BISHNOI", "352"),
    ("VINOD KUMAR", "353"),
    ("SUWA LAL KUMAWAT", "354"),
    ("VIJAY SINGH", "355"),
    ("Ajay Kumar Goutam", "356"),
    ("RAHUL", "357"),
    ("SURENDER PAL", "358"),
    ("narshi ram", "359"),
    ("DEVENDRA", "360"),
    ("KULWINDER KUMAR MATTU", "361"),
    ("BIRDA RAM BAINDA", "362"),
    ("MUNNI RAM", "363"),
    ("YASHPAL SARAN", "364"),
    ("RATHORE ASSOCIATE & MOTORS", "365"),
    ("Het Ram", "366"),
    ("Saraj Khan", "367"),
    ("Gora Associates", "368"),
    ("Kuldeep Singh", "369"),
    ("Madan Lal Shokhal", "370"),
    ("Vinod Kumari", "371"),
    ("Chena Ram Choudhary", "372"),
    ("ANEEL DOOKIYA", "373"),
    ("Rustam Bano", "374"),
    ("SAWARIYA CONTRACTORS", "375")
]

try:
    conn = psycopg2.connect(
        host="187.77.187.120",
        port=5431,
        database="meh",
        user="mehar",
        password=password
    )
    
    cursor = conn.cursor()
    
    # Insert new brokers or update existing ones
    inserted = 0
    updated = 0
    
    for name, dsa_code in brokers_data:
        # Check if broker exists
        cursor.execute("SELECT id FROM brokers WHERE name = %s", (name,))
        existing = cursor.fetchone()
        
        if existing:
            # Update existing broker with DSA code
            cursor.execute("UPDATE brokers SET dsa_code = %s WHERE name = %s", (dsa_code, name))
            updated += 1
        else:
            # Insert new broker
            cursor.execute("""
                INSERT INTO brokers (name, dsa_code, commission_rate, address, status, created_at, updated_at)
                VALUES (%s, %s, 1.50, 'JAIPUR', 'active', NOW(), NOW())
            """, (name, dsa_code))
            inserted += 1
    
    conn.commit()
    print(f"Successfully processed {len(brokers_data)} brokers:")
    print(f"- Updated: {updated} existing brokers with DSA codes")
    print(f"- Inserted: {inserted} new brokers")
    
    # Show sample of updated data
    cursor.execute("SELECT name, dsa_code FROM brokers WHERE dsa_code IS NOT NULL ORDER BY CAST(dsa_code AS INTEGER) LIMIT 10")
    sample = cursor.fetchall()
    print("\nSample brokers with DSA codes:")
    for row in sample:
        print(f"  {row[0]} - DSA: {row[1]}")
    
    conn.close()
    
except Exception as e:
    print(f"Error: {e}")