-- Add missing columns from comprehensive loan form

-- Columns from earlier migrations that might be missing
ALTER TABLE loans ADD COLUMN IF NOT EXISTS loan_number TEXT;
ALTER TABLE loans ADD COLUMN IF NOT EXISTS grid DECIMAL;
ALTER TABLE loans ADD COLUMN IF NOT EXISTS ltv DECIMAL;
ALTER TABLE loans ADD COLUMN IF NOT EXISTS co_applicant_name TEXT;
ALTER TABLE loans ADD COLUMN IF NOT EXISTS co_applicant_mobile TEXT;
ALTER TABLE loans ADD COLUMN IF NOT EXISTS guarantor_name TEXT;
ALTER TABLE loans ADD COLUMN IF NOT EXISTS guarantor_mobile TEXT;
ALTER TABLE loans ADD COLUMN IF NOT EXISTS current_address TEXT;
ALTER TABLE loans ADD COLUMN IF NOT EXISTS permanent_address TEXT;
ALTER TABLE loans ADD COLUMN IF NOT EXISTS our_branch TEXT;

-- Income Details
ALTER TABLE loans ADD COLUMN IF NOT EXISTS income_source TEXT;
ALTER TABLE loans ADD COLUMN IF NOT EXISTS monthly_income DECIMAL;
ALTER TABLE loans ADD COLUMN IF NOT EXISTS nip_ip TEXT DEFAULT 'nip';

-- Agriculture
ALTER TABLE loans ADD COLUMN IF NOT EXISTS agriculture TEXT;

-- RTO Details
ALTER TABLE loans ADD COLUMN IF NOT EXISTS vehicle_number TEXT;
ALTER TABLE loans ADD COLUMN IF NOT EXISTS rc_owner_name TEXT;
ALTER TABLE loans ADD COLUMN IF NOT EXISTS rc_mfg_date TEXT;
ALTER TABLE loans ADD COLUMN IF NOT EXISTS rc_expiry_date DATE;
ALTER TABLE loans ADD COLUMN IF NOT EXISTS hpn_at_login TEXT;
ALTER TABLE loans ADD COLUMN IF NOT EXISTS hpn_after_pdd TEXT;
ALTER TABLE loans ADD COLUMN IF NOT EXISTS rto_rc_handover_date DATE;
ALTER TABLE loans ADD COLUMN IF NOT EXISTS rto_agent_name TEXT;
ALTER TABLE loans ADD COLUMN IF NOT EXISTS agent_mobile_no TEXT;
ALTER TABLE loans ADD COLUMN IF NOT EXISTS dto_location TEXT;
ALTER TABLE loans ADD COLUMN IF NOT EXISTS challan TEXT DEFAULT 'No';
ALTER TABLE loans ADD COLUMN IF NOT EXISTS rto_papers TEXT;
ALTER TABLE loans ADD COLUMN IF NOT EXISTS for_closure TEXT DEFAULT 'No';

-- EMI Details
ALTER TABLE loans ADD COLUMN IF NOT EXISTS emi_amount DECIMAL;
ALTER TABLE loans ADD COLUMN IF NOT EXISTS total_emi INTEGER;
ALTER TABLE loans ADD COLUMN IF NOT EXISTS total_interest DECIMAL;
ALTER TABLE loans ADD COLUMN IF NOT EXISTS first_emi_amount DECIMAL;
ALTER TABLE loans ADD COLUMN IF NOT EXISTS first_installment_due_date DATE;
ALTER TABLE loans ADD COLUMN IF NOT EXISTS irr DECIMAL;
ALTER TABLE loans ADD COLUMN IF NOT EXISTS emi_mode TEXT DEFAULT 'Monthly';
ALTER TABLE loans ADD COLUMN IF NOT EXISTS vertical TEXT;

-- Insurance Details
ALTER TABLE loans ADD COLUMN IF NOT EXISTS insurance_company_name TEXT;
ALTER TABLE loans ADD COLUMN IF NOT EXISTS insured_name TEXT;
ALTER TABLE loans ADD COLUMN IF NOT EXISTS idv DECIMAL;
ALTER TABLE loans ADD COLUMN IF NOT EXISTS insurance_transfer TEXT;
ALTER TABLE loans ADD COLUMN IF NOT EXISTS insurance_hpn TEXT;
ALTER TABLE loans ADD COLUMN IF NOT EXISTS insurance_date DATE;
ALTER TABLE loans ADD COLUMN IF NOT EXISTS insurance_renewal_date DATE;

-- Deductions
ALTER TABLE loans ADD COLUMN IF NOT EXISTS file_charge DECIMAL;
ALTER TABLE loans ADD COLUMN IF NOT EXISTS loan_suraksha DECIMAL;
ALTER TABLE loans ADD COLUMN IF NOT EXISTS stamping DECIMAL;
ALTER TABLE loans ADD COLUMN IF NOT EXISTS valuation DECIMAL;
ALTER TABLE loans ADD COLUMN IF NOT EXISTS deferral_charges DECIMAL;
ALTER TABLE loans ADD COLUMN IF NOT EXISTS gst DECIMAL;
ALTER TABLE loans ADD COLUMN IF NOT EXISTS documentation_charges DECIMAL;
ALTER TABLE loans ADD COLUMN IF NOT EXISTS other_charges DECIMAL;

-- Dates
ALTER TABLE loans ADD COLUMN IF NOT EXISTS disburse_date DATE;
ALTER TABLE loans ADD COLUMN IF NOT EXISTS login_date DATE;
ALTER TABLE loans ADD COLUMN IF NOT EXISTS approval_date DATE;
ALTER TABLE loans ADD COLUMN IF NOT EXISTS disburse_branch_name TEXT;
ALTER TABLE loans ADD COLUMN IF NOT EXISTS remark TEXT;

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_loans_loan_number ON loans(loan_number);
CREATE INDEX IF NOT EXISTS idx_loans_vehicle_number ON loans(vehicle_number);
CREATE INDEX IF NOT EXISTS idx_loans_customer_id ON loans(customer_id);
